---
- hosts: localhost  # put localhost.  We are processing against aws
  connection: local  # put local.  We are processing against aws
  gather_facts: False  # don't gather facts against localhost
  vars:
    aws_access_key: ''
    aws_secret_key: ''
    instance_name: 'NameYourServer'
    key_name: 'ANSIBLE_TOWER_CLI'
    instance_type: 't2.micro' # keep it free
    image: 'ami-03cebf94e918675be' # free ami from Amazon us-east-2 region
    vpc_subnet_id: 'subnet-bc2b54c6'
    group_id: 'allow_ssh_and_awx'
    zone: 'us-east-2'
    region: 'us-east-2'
  tasks:
    - name: create an aws instance
      ec2:
         aws_access_key: "{{ aws_access_key }}"
         aws_secret_key: "{{ aws_secret_key }}"
         key_name: "{{ key_name }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         count: 1
         instance_tags:
            Name: "{{ instance_name }}"
         monitoring: no
         vpc_subnet_id: "{{ vpc_subnet_id }}"
         group_id: "{{ group_id }}"
         zone: "{{ zone }}" 
         region: "{{ region }}"
         assign_public_ip: yes
      register: ec2_instance
    - name: get volume facts
      ec2_vol_facts:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        filters:
          attachment.instance-id: "{{ ec2_instance.instance_ids }}"
      #register: volume_facts
    - name: create volume tags for instance 
      ec2_tag:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        resource: "{{ item.id }}"
        state: present
        tags:
          Name: "{{ instance_name }}"
      with_items: '{{ volume_facts.volumes }}'
    - name: capture instance facts
      ec2_instance_facts:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        instance_ids: "{{ ec2_instance.instance_ids }}"
      register: instance_facts
    - name: degug # print instance facts
      debug:
        msg: "{{ instance_facts }}"