---
- name: This simple playbook creates SSH-KEY
  hosts: target
  become: yes
  become_method: sudo 
  #connection: local
  gather_facts: false
  tasks:
      - name: let's play
        openssh_keypair: 
            path: /tmp/id_ssh_rsa
            size: 2048
        register: res 
      - debug: var=res 

#1. go to /etc/ansible/ansible.cfg and uncomment the inventory line 
#2. go to /etc/ansible/hosts file and put the IP of ur instance 
#3. run ansible-playbook -u centos create_SSH_KEY.yaml
#4. connect to your instance and go to /tmp and you'll see id_ssh_rsa id_ssh_rsa.pub keys 