---
- name: keypair adding from regions
  hosts: localhost
  vars_files: ssh_var
  tasks:
    - ec2_key: 
        name: "{{name}}" # Name of the key 
        state: present # absent # present
        key_material: "{{key_material}}" # ssh_key
        region: "{{item}}" # region location
      loop: 
        - "{{key_region_1}}"
        - "{{key_region_2}}"
        - "{{key_region_3}}"