---
- hosts: web
  become: yes
  become_method: sudo
  tasks:
    - name: update kernel to lastest
      when: ansible_distribution == "CentOS" #and amsible_distribution_major_version =="7"
      package:
        name: kernel
        state: latest
   # - name: Restart the system
   #   reboot:
        