--- #sudo pip install boto
- name: Creates Ec2 instance
  hosts: localhost
  tasks:
    - name: Create debian instance 
      ec2:
        key_name: awx-tower-sudo
        instance_type: t2.micro
        image: ami-02eac2c0129f6376b
        count: 1
        vpc_subnet_id: subnet-5df7bb73
        region: us-east-1
        assign_public_ip: yes