--- #sudo pip install boto
- name: Creates Ec2 instance
  hosts: localhost
  tasks:
    - name: Create ubuntu instance 
      ec2:
        group: ssh
        key_name: awx-tower-sudo
        instance_type: t2.micro
        image: ami-08e053c0dc7059edf
        count: 1
        vpc_subnet_id: subnet-5df7bb73
        region: us-east-1
        assign_public_ip: yes