--- #sudo pip install boto
- name: Creates Ec2 instance
  hosts: localhost
  tasks:
    - name: Create instance 
      ec2:
        key_name: "{{key_name}}"
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        count: "{{count}}"
        vpc_subnet_id: "{{vpc_subnet_id}}"
        region: "{{region}}"
        #user_data: "{{ lookup(file', 'user_data.sh')}}"code 