---
- name: install ncpa agent on instances
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Create Repo on centos6
      when: ansible_distribution == "CentOS" and ansible_distribution_version == "6"
      shell: "rpm -Uvh http://repo.nagios.com/nagios/6/nagios-repo-6-3.el6.noarch.rpm"

     

