---
# tasks file for r1soft
- block: 
  - name: Create a Repostry
    copy:
      src: r1soft.repo
      dest: /etc/yum.repos.d/r1soft.repo

  - name: Install r1soft agent
    package: 
      name: serverbackup-enterprise-agent
      state: present
    notify: R1SOFT_INSTALLED

  - name: Start Agent
    systemd:
      name: sbm-agent
      state: restarted 

  - name: Get Key
    shell: "r1soft-setup --get-key http://35.192.9.120"  
    when: ansible_distribution =="CenOS" and ansible_distribution =="7"


 