---
- name: IAM group add
  hosts: localhost
#  tasks:
#    - name: IAM group add 
#      iam_group:
#        name: testgroup1
#        state: present




  tasks:
    - name: Create Groups, 
      iam:
        iam_type: group
        name: "{{ item }}"
        state: present
      loop:
          - test1
          - test2 
    #    register: new_groups        
 