---
- name: IAM user add
  hosts: localhost
#  vars_files:
#    - IAM _user_add_var
  tasks:
    - name: IAM user add with password (console access) 
      iam:
        iam_type: user
        name: "{{ name }}"                    # Type name of the user
        state: present                      
        password: "{{ password }}"            # Create user password