---
- name: Creates VPC
  hosts: localhost
  gather_facts: yes
  vars_files: subnet_vars
  #  - name: Creates subnets
  tasks:
    - name: create subnet a
      ec2_subnet:
        state: present
        region: "{{region}}"
        vpc_id: "{{vpc.id}}"
        cidr: "{{cidr}}"
        az: "{{az}}"
        resource_tags:
          Name: Db_Subnet1 

    - name: create subnet b
      ec2_subnet:
        state: present
        region: "{{region}}"
        vpc_id: "{{vpc.id}}"
        cidr: "{{cidr}}"
        az: "{{az}}"
        resource_tags:
          Name: Db_Subnet2 

    - name: create subnet c
      ec2_subnet:
        state: present
        region: "{{region}}"
        vpc_id: "{{vpc.id}}"
        cidr: "{{cidr}}"
        az: "{{az}}"
        resource_tags:
          Name: Db_Subnet3 
      register: db_subnet