---
- name: vpc create
  hosts: localhost
  gather_facts: yes
  vars_files: vpc_vars
  tasks:
    - name: create vpc in region
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_cidr_block}}"
        region: "{{vpc_region}}"
        tags: 
          module: "{{environment_name}}"
      register: vpc