---
- name: Creates VPC
  hosts: localhost
  gather_facts: yes
  vars_files: subnet_vars
  #  - name: Creates subnets
  tasks:
    - name: create subnet a
      ec2_vpc_subnet:
        state: present
        region: "{{vpc_region}}"
        vpc_id: "{{vpc.vpc.id}}"
        cidr: "{{subnet_cidr_a}}"
        az: "{{az_a}}"

    - name: create subnet b
      ec2_vpc_subnet:
        state: present
        region: "{{vpc_region}}"
        vpc_id: "{{vpc.vpc.id}}"
        cidr: "{{subnet_cidr_b}}"
        az: "{{az_b}}"

    - name: create subnet c
      ec2_vpc_subnet:
        state: present
        region: "{{vpc_region}}"
        vpc_id: "{{vpc.vpc.id}}"
        cidr: "{{subnet_cidr_c}}"
        az: "{{az_c}}"