--- #sudo pip install boto
- name: Creates Ec2 instance
  hosts: localhost
  tasks:
    - name: Create ubuntu instance 
      ec2:
        group: ssh
        key_name: awx-tower-sudo
        instance_type: t2.micro
        image: ami-076e36b130f0652ac
        count: 1
        vpc_subnet_id: subnet-ddf5b781
        region: us-east-1
        assign_public_ip: yes