---
- name: IAM Create a role and attach a managed policy
  hosts: localhost
  tasks:
    - name: IAM add role
      iam_role:
        name: "{{name}}"         #please write a name to the role   Ex:MyRole
        assume_role_policy_document: "{{ lookup('file', 'roles_vars') }}" # ex:power_roll
        description: "{{description}}" # please write description like "This is My New Role"
        state: present    # present # absent 
        managed_policy:
      #    - arn:aws:iam::aws:policy/PowerUserAccess
      #    - arn:aws:iam::aws:policy/AdministratorAccess
      #    - arn:aws:iam::aws:policy/AmazonEC2FullAccess
      #    - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess


